name:                excercises
version:             1.0.0.0
license:             BSD3

default-extensions:
- GADTs
- RankNTypes
- DeriveFunctor
- DeriveGeneric
- OverloadedStrings
- LambdaCase
- MultiParamTypeClasses
- ExplicitNamespaces
- TypeApplications
- ScopedTypeVariables
- TypeOperators
- TypeFamilies
- DataKinds
- FlexibleContexts
- FlexibleInstances
- PatternSynonyms
- PolyKinds
- DefaultSignatures
- ConstraintKinds
- NamedFieldPuns
- TupleSections
- ViewPatterns
- MultiWayIf
- RecordWildCards

dependencies:
- base >= 4.7 && < 5
- bytestring
- aeson
- aeson-pretty
- mtl
- directory
- filepath
- process
- extra
- containers
- random
- free
- memory
- transformers
- template-haskell
- text
- newtype-generics
- lens
- stm

library:
  source-dirs:
  - src
  ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -fhide-source-paths

executables:
  excercises:
    main:                Main.hs
    source-dirs:         src/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
